# Generated by Django 2.2.4 on 2020-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(default=0)),
                ('time', models.DateTimeField(verbose_name='candle opened at')),
                ('candle_open', models.DecimalField(decimal_places=5, max_digits=15)),
                ('candle_high', models.DecimalField(decimal_places=5, max_digits=15)),
                ('candle_low', models.DecimalField(decimal_places=5, max_digits=15)),
                ('candle_close', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
        ),
    ]
