# Generated by Django 2.2.4 on 2020-01-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200122_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='c',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='h',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='l',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='o',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='volume',
            field=models.CharField(max_length=50),
        ),
    ]
