# Generated by Django 2.2.4 on 2020-01-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_candle_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aroon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.CharField(max_length=30)),
                ('down', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
