# Generated by Django 2.2.4 on 2020-02-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200128_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chaikin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.CharField(max_length=20)),
                ('low', models.CharField(max_length=20)),
                ('close', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ssl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssl', models.CharField(max_length=20)),
            ],
        ),
    ]
